CHANGELOG.md
src/graphql/account.rs

From the GraphQL APIs `signIn` and `refreshToken`, the username field has been removed from the `AuthPayload` return object. This is due to redundancy as the caller of `signIn` or `refreshToken` already possesses knowledge of the username.

Remove username from AuthPayload

---

CHANGELOG.md
src/graphql.rs
src/graphql/traffic_filter.rs

* Change to send empty rules to `Piglet` to clear applied traffic filtering rules
* Change to use `host_id` instead of `agent_id@host_id` to manage traffic filtering rules

Send empty traffic filtering rules to piglet to clear applied rules

---

CHANGELOG.md
examples/minireview.rs
src/graphql.rs
src/graphql/allow_network.rs
src/graphql/block_network.rs
src/graphql/customer.rs
src/graphql/node.rs
src/graphql/node/crud.rs

* Add function to broadcast internal/allow/block networks to all Hogs
* `internal networks` is the networks of customer assigned to review node
- When a new node with review is inserted, the customer networks of the node is broadcasted.
- When the customer of review node is changed, the networks of new customer is broadcasted.
- When the customer networks of review node is changed, the changed networks is broadcasted.
- `internal networks` includes all of the `Intranet`, `Extranet`, `Gateway` addresses of customer.
The networks are defined as following:
```rust
struct HostNetworkGroup {
hosts: Vec<IpAddr>,
networks: Vec<IpNet>,
ip_ranges: Vec<RangeInclusive<IpAddr>>,
}
```

Broadcast internal/allow/block networks to all Hogs

---

CHANGELOG.md
src/graphql/allow_network.rs
src/graphql/block_network.rs
src/graphql/customer.rs
src/graphql/sampling.rs

Fix broadcast internet networks, allow/block list values to serialize with `bincode::DefaultOptions::new()`

fix broadcast internal networks, allow/block list values to hog

---

CHANGELOG.md
Cargo.toml
src/graphql/event.rs
src/graphql/node.rs
src/graphql/node/status.rs

- Added the fields of the `Event` enum internal struct provided via GraphQL. The added fields are used for more detailed `detect event filtering`.
- Added a `ping` field to `NodeStatus` struct. The added fields are available through the `NodeStatusList` query.
- Modify `status::laod` function so that the `NodeStatusList` query returns a ping field.
reference: https://github.com/aicelab/sasui/issues/2

Add fields to `NodeStatus` and `Event`

---

src/graphql/allow_network.rs
src/graphql/block_network.rs

Hog use `bincode::DefaultOptions::new().deserialize()` method to deserialize the broadcasted internal network/allow/block list from REview.
I changed this last week but it's overwrited. Now I recover the change.

change serialize method

---

CHANGELOG.md
src/graphql/event.rs

To maintain consistency, change the type of `port` number to `u16` from `String`.
* `TorConnection` and `RepeatedHttpSessions` event

Modify the type of port to u16 of TorConnection and RepeatedHttpSessions event

---

CHANGELOG.md
Cargo.toml
src/graphql/outlier.rs

Added separate method to search ranked outliers for search.

 Add search filter for ranked outliers

---

CHANGELOG.md
Cargo.toml
src/graphql/outlier.rs

Change the type of `id` in `ranked_outlier`/`saved_outlier` queries to `StringNumber`

---

CHANGELOG.md
Cargo.toml
src/graphql/outlier.rs

- Change the distance search criteria to support a single search.
- Change the type of id in the `Rankedoutlier` field from `StringNumber` to `ID`.
- Change the part about `RankedOutlierTotalCount` to count the total count differently.
- Bump version to 0.15.0
Closes: #83, #87, #88

Modify `ranked outliers` distance search condition & Release 0.15.0

---

CHANGELOG.md
Cargo.toml
src/graphql/outlier.rs

- Change the distance search criteria to support a single search.
- Change the type of id in the `Rankedoutlier` field from `StringNumber` to `ID`.
- Change the part about `RankedOutlierTotalCount` to count the total count differently.
- Bump version to 0.15.0
Closes: #83, #87, #88

Modify `ranked_outliers` distance search condition & Release 0.15.0

---

CHANGELOG.md
Cargo.toml
src/graphql.rs
src/graphql/data_source.rs
src/graphql/outlier.rs

Added a grapqhl subscription to periodically send the stored `ranked outliers`. 
This feature is currently used by `L Project` to transfer all the `ranked outliers` stored on the lower server to the upper server, but it is necessary because we will need this structure in our product in the future.

Added `rankedOutlierStream` Graphql API to fetch `ranked outlier` periodically

---

src/graphql/node.rs
src/graphql/node/crud.rs
src/graphql/node/input.rs

Modify fields in `Node`

---

CHANGELOG.md
Cargo.toml
src/graphql/category.rs
src/graphql/event.rs
src/graphql/event/log.rs
src/graphql/event/network.rs
src/graphql/event/sysmon.rs

- Update review-database to 0.23.0.
- Add WindowsThreat event for windows sysmon events.
- Add NetworkThreat event for network events.
- Add ExtraThreat event for misc events.

Added new three detection events

---

CHANGELOG.md
Cargo.toml
examples/minireview.rs
src/graphql.rs
src/graphql/event.rs
src/graphql/outlier.rs
src/graphql/sampling.rs
src/graphql/semi_model.rs
src/graphql/triage.rs
src/graphql/triage/policy.rs

This PR is for a feature that is only used in rio projects.
- Added graphql queries for triage and outliers.
- Added graphql queries for semi-supervised model.
- Added `agent_id` for filtering agent id to `EventListWithTriageFilterInput`.
- Added new fields to the sampling policy's enum Interval.

Add new graphql qeury

---

CHANGELOG.md
src/graphql.rs
src/graphql/account.rs

This resolved an issue in the GraphQL API where the ordering of edges was inconsistent when using `last`/`before` pagination arguments. According to the GraphQL Cursor Connections Specification, the order of edges should remain the same whether using `first`/`after` or `last`/`before`, provided all other arguments are equal. Previously, our API returned edges in reverse order when `last`/`before` was used, which was contrary to the specification.

Fix GraphQL pagination ordering

---

CHANGELOG.md
Cargo.toml
src/graphql/node.rs
src/graphql/node/crud.rs

Close: #117 
Add two new fields to `Node` for `Revert` and set fields when creating new `Node`

Add fields to Node for revert

---

src/graphql.rs
src/graphql/account.rs

Avoid using `MapIterator`, which requires the internal format of the database, and use `Table<Account>::iter` instead.
Closes #45.

Do not assume the internal format of the database

---

src/graphql/cluster.rs
src/graphql/outlier.rs

This also fixes clippy warnings with Rust 1.76.

Remove unused arguments

---

CHANGELOG.md
src/graphql/customer.rs

Closes: #140 ; Closes: #139
`Outlier` and `RankedOutlier` ordering does not need to be changed. However, some APIs including `Customers` does not have unit tests to check the ordering of edges and some may use `load` differently.  In doing so, unit tests are required to confirm. This PR is test case for `Customers` first and the two APIs that need unit tests (`NodeStatusList` and `AccountList`) will come in a different PR.

Add test for checking ordering of customers

---

CHANGELOG.md
src/auth/jwt.rs
src/graphql/account.rs

This PR changes the type for JWT expiration time in GraphQL query from `i64` to `i32`, which is suggested in #37. Also, internally the expiration time is treated as `u32`, rather than `i64`, for better compile-time type checking.

Use stricter time checking for JWT expiration

---

CHANGELOG.md
examples/minireview.rs
src/graphql.rs
src/graphql/node/control.rs
src/graphql/node/process.rs
src/graphql/node/status.rs
src/graphql/sampling.rs

* Pending: #150 (The CI fails because of the deprecated methods in chrono-0.4.35. The PR needs to be rebased after the issue has been resolved.)
The PR Adds the following methods to `AgentManager`:
- `AgentManager::broadcast_crusher_sampling_policy` method to broadcast the
sampling policy to the Crusher agents.
- `AgentManager::get_process_list` method to retrieve the list of processes usage running on host. It returns a `Vec` of `graphql::Process`.
- `AgentManager::get_resource_usage` method to retrieve the resource usage of a host. It returns `graphql::ResourceUsage`.
- `AgentManager::ping` method to measure the latency between the agent manager and a host.
- `AgentManager::reboot` method to reboot a host.
This is a part of #144.

Add messaging functions to `AgentManager`

---

Cargo.toml
src/graphql/allow_network.rs
src/graphql/block_network.rs
src/graphql/category.rs
src/graphql/cluster.rs
src/graphql/event.rs
src/graphql/network.rs
src/graphql/qualifier.rs
src/graphql/status.rs
src/graphql/tags/network_tag.rs

* Pending: #151
- `Store::network_tag_set` now returns `TagSet`, rather than `IndexedSet`.
- Use `IndexedTable::get_by_id`, a routine replacing multiple, near-identical methods.

Adapt to review-database's API change in review-database-0.26

---

CHANGELOG.md
src/graphql.rs
src/graphql/node/control.rs
src/graphql/node/process.rs
src/graphql/node/status.rs
src/graphql/sampling.rs

This PR replaces the protocol-level implementations of agent communication with corresponding methods in `AgentManager` for the following methods:
- `broadcast_crusher_sampling_policy`
- `get_process_list`
- `get_resource_usage`
- `ping`
- `reboot`
This is a part of #144.

Use `AgentManager`'s newly-added methods

---

CHANGELOG.md
examples/minireview.rs
src/graphql.rs
src/graphql/node/control.rs

This will be used by GraphQL API `nodeShutdown`.
A part of #144.

Add `AgentManager::halt`

---

CHANGELOG.md
src/graphql/node/status.rs

Added unit test for `nodeStatusList`.  It seems like `accountList` already has unit test in regards to pagination ordering.
Closes: #146 ; Closes: #180 ;

Add unit test for nodeStatusList

---

Cargo.toml
examples/minireview.rs
src/graphql.rs
src/graphql/node.rs
src/graphql/node/control.rs
src/graphql/node/status.rs

This pull request addresses the issue in `oinq` regarding its structure and modularity, as described in petabi/oinq#60. Currently, `oinq` serves as a comprehensive package for implementing the communication protocol within the REview ecosystem, relying on QUIC for efficient and secure communication. However, to promote code reuse and collaboration among projects utilizing QUIC, it's proposed to refactor `oinq` into two separate crates:
1. **`oinq`**: This crate will focus solely on low-level network communication, such as sending and receiving messages and streams.
2. **`review-protocol`**: Built on top of `oinq`, this crate will implement the application-specific protocol for the REview ecosystem.
This pull request implements the proposed changes by replacing direct dependencies on …

Refactor dependencies to use review-protocol crate

---

CHANGELOG.md
Cargo.toml
src/graphql/event.rs
src/graphql/node.rs
src/graphql/node/control.rs
src/graphql/node/crud.rs
src/graphql/node/input.rs

closes #196 
Updating review-database to 0.27.0 requires changing names of structs, fields, and variables, that are related to `Node`.

Update review-database to 0.27.0

---

CHANGELOG.md
examples/minireview.rs
src/graphql.rs
src/graphql/node/control.rs

* Pending: #201
`broadcast_to_crusher` is no longer used and shouldn't be used in the future, since it assumes review-web knows the protocol between REview and agents. See #144 for background.

Remove unused function from `AgentManager`

---

.github/workflows/ci.yml

This PR addresses an issue where linking with the pq-sys crate was failing on macOS 14 due to an inability to locate the libpq library. The issue was identified following a query from @sehkone, who asked about persistent CI errors related to this problem. The root cause was Homebrew's change in its default installation directory, shifting from `/usr/local` to `/opt/homebrew`. The pq-sys crate was still attempting to access the library in the old location. To resolve this, we have explicitly passed the correct library directory to pq-sys using an environment variable, ensuring proper linkage.
While this query was raised via a private email, we encourage the use of GitHub issues for such inquiries in the future. This allows for more transparent, collaborative tracking and discussion of the …

Configure pq-sys for GitHub Actions on macOS 14

---

CHANGELOG.md
src/graphql.rs

- Remove `default` function that returns error from trait `AgentManager`
Close: #212

Remove `AgentManger::default`

---

CHANGELOG.md
Cargo.toml
src/graphql/account.rs

- Refactored initialization code in `set_initial_admin_password` to check for the presence of the `REVIEW_ADMIN` environment variable `admin:password`. If available, parses the variable to obtain the username and password for the initial administrator account. Returns an error if the REVIEW_ADMIN variable is invalid or unavailable. This change eliminates hardcoded credentials, improving security and flexibility.
Close: #38

Change admin account to read `REVIEW_ADMIN` env variable

---

CHANGELOG.md
examples/minireview.rs
src/backend.rs
src/graphql.rs
src/lib.rs

This pull request refactors the structure of `review-web` to improve clarity and usability. Specifically, it relocates the `AgentManager` and `CertManager` traits from the `graphql` module to a new `backend` module. Additionally, it exposes the `Config` type in the public API to ensure all types used by the public traits are accessible.
The `AgentManager` and `CertManager` traits, while utilized in the context of the GraphQL API, are fundamentally backend management tools. Their placement in the `graphql` module could cause confusion or misinterpretation about their purpose and usage. By moving them to a `backend` module, we clarify their roles and streamline the architecture of the crate.
Moreover, exposing `Config` publicly aligns with Rust's guidelines on API transparency and …

Refactor code structure and expose `Config`

---

Cargo.toml
src/graphql.rs
src/graphql/account.rs
src/graphql/allow_network.rs
src/graphql/block_network.rs
src/graphql/category.rs
src/graphql/cluster.rs
src/graphql/customer.rs
src/graphql/data_source.rs
src/graphql/event.rs
src/graphql/model.rs
src/graphql/network.rs
src/graphql/node/crud.rs
src/graphql/node/status.rs
src/graphql/outlier.rs
src/graphql/qualifier.rs
src/graphql/sampling.rs
src/graphql/statistics.rs
src/graphql/status.rs
src/graphql/template.rs
src/graphql/tor_exit_node.rs
src/graphql/triage/policy.rs
src/graphql/triage/response.rs
src/graphql/trusted_domain.rs
src/graphql/trusted_user_agent.rs

The PR adjusts `review-web` to the updated `outlier` map interface from `review-database` where `Map` is no longer exposed and the key is stored differently. To fit in, the following modifications have been made.
* `load_nodes`, `load_nodes_with_filter`, `load_with_filter`, `iter_to_nodes_with_filter` are refactored for clarity.
* `validate_and_process_pagination_params` as a validation process for `load_edges` and `load_edges` is excluded from individual query (before the load function call) to avoid duplicated decoding error.
* Switches cursor encoding format from `encode(before):encode(after)` to `encode(serialize(&(before,after)))` for security for `outlier::load`.
* Refactors `outlier::load_ranked_outliers_with_filter`, `outlier::load_with_all_outlier` and functions related for …

Update `outlier` interface

---

CHANGELOG.md
src/graphql/account.rs

- Update signIn function to retrieve max_parallel_sessions field for each sign-in attempts
- Test signIn function to verify correct behavior when limit is exceeded
Close: #40

Add session limitation

---

CHANGELOG.md
src/graphql.rs
src/graphql/account.rs
src/graphql/node/control.rs
src/graphql/node/status.rs
src/lib.rs

- Update `graphql_handler` to include client IP in requests.
- Modify `signIn` to validate IP against `allowAccessFrom`.
- Update `TestSchema` to accept `test_addr` for simulating client IP.
Close: #39

Add IP-based access control

---

src/graphql/node.rs

resolve #231 
In this commit, the schema of the graphql playground is as follows.

Add specific type definitions for `StringNumber` in `NodeStatus`

---

CHANGELOG.md
Cargo.toml
src/graphql/node.rs
src/graphql/node/control.rs
src/graphql/node/crud.rs
src/graphql/node/input.rs
src/graphql/node/status.rs
src/graphql/sampling.rs

Cargo.toml의 review-database, review-protocol 버전 확인 필요
- Removed central server's address fields.
- Removed `reconverge_giganto_[ip|port]` fields.
- Removed `html` field.
- Added `vbs` field.
- Merged `protocols` (boolean) and `protocol_list` (`HashMap<String, bool>`) into
`protocols: Option<Vec<String>>`.
- The new `protocols` field should be sorted in alphabetical order.
- Merged `sensors` (boolean) and `sensor_list` (`HashMap<String, bool>`) into
`sensors: Option<Vec<String>>`.
- The new `sensors` field should also be sorted in alphabetical order.
- The `get_node_settings` function will be removed in the future.
- Until it is removed, each `Setting` element returned by `get_node_settings`
in `Result<Vec<Setting>>` will have the following fields always set to `0.0.0.0:0`.
- `piglet.rpc` …

Modify the NodeSettings

---

CHANGELOG.md
src/graphql/outlier.rs

Close #50
change response in preserveOutliers api
origin : `Result<usize>`  
new : `Result<Vec<PreserveOutliersOutput>>`
Add value to `Vec<PreserveOutliersOutput>` only when `update_is_saved` result is false

Modify `preserveOutliers` GraphQL API

---

src/auth/jwt.rs

This PR simplifies the implementation of `JWT_EXPIRES_IN` and `JWT_SECRET` in src/auth/jwt.rs by removing the unnecessary use of `Arc`.
Closes #277.

Remove unnecessary `Arc` from `LazyLock`

---

CHANGELOG.md
examples/minireview.rs
src/backend.rs
src/graphql.rs
src/graphql/node/control.rs
src/graphql/node/status.rs

This refactor improves the flexibility and accuracy of the `ping` method, making it more robust and aligned with Rust's time handling conventions.
Resolves #274.

Refactor `AgentManager::ping` to return `Duration`

---

CHANGELOG.md
Cargo.toml
src/graphql/account.rs

Close: https://github.com/aicers/review-web/issues/250
Among the list of tasks I needed to perform was the following items.
- Modify account, insert_account, modify_account, and other related APIs in review-web as needed to support the field.
- Add two new APIs in review-web: one for retrieving the user's language setting, and another for updating it.
However, after looking at the existing code, I found that the original purpose could be achieved just by modifying the existing API rather than adding new APIs, so I worked on adding language-related codes to the existing function without adding separate new APIs. But, I think there could be some misunderstanding about these task so before I open the PR to merge, I have just opened the draft PR and I ask you to review the code I worked on. …

Modify related APIs due to addition of language field in Account

---

CHANGELOG.md
src/graphql/node.rs
src/graphql/node/status.rs

This PR changes the `ping` field in `NodeStatus` in GraphQL API from `StringNumber`, a custom scalar type, to `Float`, a built-in scalar type.
Resolves #282.

Use `f64` for `ping` field in `NodeStatus`

---

CHANGELOG.md

The entry in CHANGELOG should describe the change against the last release. This commit fixes the entry for the `ping` field in the GraphQL API so that it is compared against the last release rather than the last commit before the change.
This corrects #283, which has resolved #282. Documentation change only.

Fix CHANGELOG entry for `ping` in GraphQL API

---

src/graphql/node/crud.rs
src/graphql/node/input.rs

- Updated `create_draft_update` to ensure `name_draft` is not dependent on `new.profile_draft`.
Closes: #284

Fix `create_draft_update`

---

CHANGELOG.md
Cargo.toml
src/graphql/tidb.rs

Close #294 
Add `category` field to TI db and rules.
I divided the PR #255 into smaller pieces because its too large change. This is the first PR.

Add category field to TI db and rules

---

CHANGELOG.md
Cargo.toml
src/graphql/event.rs
src/graphql/event/conn.rs
src/graphql/event/dcerpc.rs
src/graphql/event/dns.rs
src/graphql/event/ftp.rs
src/graphql/event/group.rs
src/graphql/event/http.rs
src/graphql/event/kerberos.rs
src/graphql/event/ldap.rs
src/graphql/event/log.rs
src/graphql/event/mqtt.rs
src/graphql/event/network.rs
src/graphql/event/nfs.rs
src/graphql/event/ntlm.rs
src/graphql/event/rdp.rs
src/graphql/event/smb.rs
src/graphql/event/smtp.rs
src/graphql/event/ssh.rs
src/graphql/event/sysmon.rs
src/graphql/event/tls.rs

Close #244 
- Add `category` field to all the detected events
- Add new fields to `TorConnection` event.
- `orig_filenames`, `orig_mime_types`, `resp_filenames`, `resp_mime_types`,
`post_body`, `state`
- Add new fields to `BlockListConn` event.
- `orig_l2_bytes`, `resp_l2_bytes`
I divided the PR #255 into smaller pieces because its too large change. This is the second PR.

Insert category field to the detected event fields

---

CHANGELOG.md
src/graphql/account.rs

Close: #268 
I added two APIs(functions) in this work. One is a function that takes username as a parameter and returns the language of the corresponding account(L422~L425 in `account.rs`), and the other is a function that takes username as a parameter and modifies the language of the corresponding account. 
~~However, while writing the test code, I found that if we ask for account query, we can get the value of the language field. I wasn't sure if we really need the first function.~~
I thought maybe I was misunderstanding the work I was assigned. So I opened work on #268 issue with draft PR. I would sincerely appreciate it if you could comment on my work, and if there is anything I misunderstood, I will immediately correct it and continue the work. @sophie-cluml  @sehkone

Add the functions to get and update user's language setting

---

CHANGELOG.md
Cargo.toml
src/graphql/node/control.rs

Fix `applyNode` GraphQL API

---

src/graphql/model.rs

This PR simplifies the `topClustersByScore` implementation in the GraphQL API by removing the call to `Database::get_top_clusters_by_score`, which always returns an empty set. Instead, we directly return an empty `ClusterScoreSet`, reducing unnecessary calls and preventing future compile errors when `review-database` is updated to version 0.31.
- Issue [#309](https://github.com/aicers/review-web/issues/309) proposes deleting the `topClustersByScore` API, as it no longer provides meaningful data.
- The underlying implementation depends on the `csv_indicator` table in the database, which is no longer populated (refer to [petabi/review-database#341](https://github.com/petabi/review-database/issues/341)).
- The table and the API itself are slated for deletion in review-database 0.31.0.
This …

Simplify `topClustersByScore` implementation

---

src/graphql/model.rs

`ClusterScoreSet` and `ClusterScore` should no longer rely on their counterparts in review-database. They will be deleted from review-database in a future release.
No functional changes are intended in this PR.

Simplify ClusterScoreSet in GraphQL API

---

CHANGELOG.md

I noticed that the heading level in our CHANGELOG was a bit off. This tiny PR bumps the `Fixed` section from H2 (`##`) to H3 (`###`) to keep our hierarchy consistent.

Correct heading level in CHANGELOG

---

CHANGELOG.md
Cargo.toml
src/graphql.rs
src/graphql/node/status.rs
src/graphql/outlier.rs

This PR updates review-database to version 0.31.0, which includes a bug fix that's crucial for our application at @petabi. We'd greatly appreciate it if this update could be included in the next release of review-web.
The changes in this PR are minimal, only adapting to the API change in review-database, and shouldn't introduce any functional changes. 
Note that this PR is built on top of the changes in #318, so it's best to review and merge that one first to avoid any conflicts.

Update review-database to 0.31.0

---

CHANGELOG.md
src/graphql/ip_location.rs

The UI will add a dashboard feature where a rotatable and zoomable earth globe displays threat flows, each of which starts from a source IP location and ends at a destination IP location. To enable this feature, the UI needs to retrieve the list of multiple IP locations in a single request, but the current interface only supports retrieving the location for one IP address at a time.
To prevent performance degradation, this API limits the maximum number of IP addresses to 200 for returning location information.

Introduce a new GraphQL API, `ipLocationList`

---

CHANGELOG.md
examples/minireview.rs
src/backend.rs
src/graphql.rs
src/graphql/allow_network.rs
src/graphql/block_network.rs
src/graphql/customer.rs
src/graphql/node/control.rs
src/graphql/node/status.rs

This PR modifies the methods in `AgentManager` trait to accept `HostNetworkGroup` directly instead of its serialized form. By doing so, we allow the review-protocol crate to handle serialization, which is a more suitable place for this responsibility.
This change is required for petabi/review-protocol#13.

Decouple `AgentManager` from serialization

---

CHANGELOG.md
src/graphql/outlier.rs

- Fix to return results from the `rankedOutliers` GraphQL API in ascending order.
- Fix the `rankedOutliers` GraphQL API so that when called `rankedOutliers` with a cursor, the `RankedOutlier` value corresponding to that cursor is excluded from the returned results.
Fix: #330

Fix `rankedOutliers` GraphQL API

---

CHANGELOG.md
src/graphql.rs
src/graphql/account.rs
src/graphql/allow_network.rs
src/graphql/block_network.rs
src/graphql/category.rs
src/graphql/cluster.rs
src/graphql/customer.rs
src/graphql/data_source.rs
src/graphql/model.rs
src/graphql/network.rs
src/graphql/node/crud.rs
src/graphql/node/status.rs
src/graphql/qualifier.rs
src/graphql/sampling.rs
src/graphql/slicing.rs
src/graphql/statistics.rs
src/graphql/status.rs
src/graphql/template.rs
src/graphql/tor_exit_node.rs
src/graphql/triage/policy.rs
src/graphql/triage/response.rs
src/graphql/trusted_domain.rs
src/graphql/trusted_user_agent.rs

Closes #328 
These two wrappers, `graphql::query` and `graphql::query_with_contraints` resolve the issue and revert the regression affecting several APIs, such as `clusters`.

Refactor code to avoid redundant query validation

---

CHANGELOG.md
src/graphql/outlier.rs

- Modify to search for outliers whose distance value greater than or equal to the start value.
- Fix to apply filtering on the first element of `OutlierInfo` iter.
- Remove unused `to` variable and related code in `rankedOutliers`.
- Remove unnecessary `continue` that is performed after checking the number of outliers.
Close: #338
Close: #337

Change the distance search condition for `rankedOutliers`

---

Cargo.toml

The crypto provider used by rustls in review-web has been changed to ring, which is already used by review-database. This avoids compiling multiple crypto providers and promotes consistency across dependencies.
Resolves #343.

Use ring as crypto provider in rustls for consistency

---

src/graphql.rs
src/graphql/cluster.rs
src/graphql/model.rs
src/graphql/slicing.rs
src/graphql/statistics.rs

async-graphql's `query` function automatically handles cursor encoding and decoding. This commit removes the custom cursor encoding/decoding code from the `slicing` module and uses async-graphql's built-in functionality instead. This change only updates the `slicing` module to keep the PR minimal, and a follow-up change will be needed to address the top-level `encode_cursor` and `decode_cursor` functions in the `graphql` module.

Let async-graphql handle cursor encoding/decoding

---

CHANGELOG.md
src/graphql/node/control.rs

Prevent agent notification if `draft` is empty

---

CHANGELOG.md
src/graphql/event.rs
src/graphql/event/group.rs
src/graphql/sampling.rs

Close: #346 
Modified `samplingPolicy` and `samplingPolicyList` GraphQL API to have `node` field in their response.

Fix sampling policy related APIs

---

CHANGELOG.md
Cargo.toml
src/graphql.rs
src/graphql/event.rs
src/graphql/node.rs
src/graphql/node/control.rs
src/graphql/node/crud.rs
src/graphql/node/status.rs

- Update review-database to 0.32.0
- Rename `AgentKind` enum variants to align with review-database
- Add `TimeSeriesGenerator` variant
- Update relevant test cases
Close: #351

Update `AgentKind` enum variants

---

CHANGELOG.md
src/graphql/account.rs

Close #14
Changed `signIn` GraphQL API logic.
- Returns `Err` if `last_signin_time` of `account` is `None`.

Add signInWithNewPassword GraphQL API

---

CHANGELOG.md
src/archive.rs
src/graphql.rs
src/graphql/account.rs
src/graphql/allow_network.rs
src/graphql/block_network.rs
src/graphql/category.rs
src/graphql/customer.rs
src/graphql/data_source.rs
src/graphql/filter.rs
src/graphql/network.rs
src/graphql/node.rs
src/graphql/node/crud.rs
src/graphql/node/status.rs
src/graphql/outlier.rs
src/graphql/qualifier.rs
src/graphql/sampling.rs
src/graphql/statistics.rs
src/graphql/status.rs
src/graphql/template.rs
src/graphql/tor_exit_node.rs
src/graphql/triage/policy.rs
src/graphql/triage/response.rs
src/graphql/trusted_domain.rs
src/graphql/trusted_user_agent.rs
src/lib.rs

Close #355
The following sources are the main areas that have been modified.
graphql.rs
graphql directory sub-source
The rest of the changes are fixes for Clippy errors caused by the
Rust version update.

Update GraphQL cursor to use `OpaqueCursor`

---

src/graphql/account.rs

Since `SocketAddr` is `Copy` and small enough, it's better to pass it by value.

Use pass-by-value for SocketAddr

---

CHANGELOG.md
Cargo.toml
src/graphql.rs
src/graphql/cluster.rs
src/graphql/model.rs
src/graphql/slicing.rs
src/graphql/statistics.rs

This replaces the custom cursor encoding and decoding logic with the `OpaqueCursor` type provided by `async-graphql`. This simplifies the code and reduces the risk of errors in cursor handling.
Note that this change breaks backwards compatibility with older versions of the GraphQL API, as the cursor format has changed.

Replace custom cursor encoding with OpaqueCursor

---

src/archive.rs
src/graphql.rs

This PR removes unnecessary `std::` prefixes from type names throughout the codebase, improving readability and consistency.
The changes are purely cosmetic and do not affect the functionality of the code.

Remove redundant std:: prefix from type names

---

CHANGELOG.md
src/graphql.rs
src/graphql/trusted_domain.rs

Add `updateTrustedDomain` GraphQL API

---

CHANGELOG.md
Cargo.toml
README.md
src/graphql/event.rs
src/graphql/event/bootp.rs
src/graphql/event/conn.rs
src/graphql/event/dcerpc.rs
src/graphql/event/dhcp.rs
src/graphql/event/dns.rs
src/graphql/event/ftp.rs
src/graphql/event/group.rs
src/graphql/event/http.rs
src/graphql/event/kerberos.rs
src/graphql/event/ldap.rs
src/graphql/event/log.rs
src/graphql/event/mqtt.rs
src/graphql/event/network.rs
src/graphql/event/nfs.rs
src/graphql/event/ntlm.rs
src/graphql/event/rdp.rs
src/graphql/event/smb.rs
src/graphql/event/smtp.rs
src/graphql/event/ssh.rs
src/graphql/event/sysmon.rs
src/graphql/event/tls.rs
src/graphql/node.rs
src/graphql/node/status.rs
src/graphql/outlier.rs
src/graphql/triage.rs
src/graphql/triage/response.rs

Rename source to sensor

---

.markdownlint.yaml
CHANGELOG.md
src/graphql.rs
src/graphql/account.rs
src/graphql/ip_location.rs
src/graphql/node.rs
src/graphql/sampling.rs

Close #353
`Nic` and `NicInput` that are not used as additional content have been
removed.

Added `IpAddress` GraphQL scalar for IP addresses

---

CHANGELOG.md
Cargo.toml
src/graphql/account.rs
src/graphql/ip_location.rs

Closes: #370 
Closes: #371 
- Modified related APIs to accommodate the addition of `theme` field in `Account`
- Added new APIs to retrieve and update the user's screen color theme selection

Add `theme` field to `Account` and modify the related APIs

---

CHANGELOG.md
Cargo.toml
examples/minireview.rs
src/graphql.rs
src/graphql/account.rs
src/graphql/event.rs
src/graphql/event/group.rs
src/graphql/ip_location.rs
src/lib.rs

NOTE: This PR builds upon #372. The branch needs to be rebased after #372 has been merged.
The `ip2location::DB` argument for `serve` no longer needs to be wrapped in `Arc` and `Mutex`. This change simplifies the code and improves performance by removing unnecessary locking.

Remove unnecessary Mutex for ip2location database

---

CHANGELOG.md
Cargo.toml
src/graphql/event/http.rs
src/graphql/event/log.rs
src/graphql/event/network.rs
src/graphql/event/sysmon.rs
src/graphql/model.rs

Close #384 
Modify the type of `cluster_id` field of the detection event structures from `usize` to `Option<usize>`:
- `HttpThreat`, `ExtraThreat`, `NetworkThreat`, `WindowsThreat`

Modify the cluster_id type `usize` to `Option<usize>`

---

CHANGELOG.md
src/graphql/account.rs

This PR removes the `reset_admin_password` function from the `graphql::account` module, as it has been obsoleted by the `resetAdminPassword` GraphQL API mutation.
The `reset_admin_password` function was previously used by the QUIC API, but since the QUIC API has been replaced with the GraphQL API mutation instead, this function is no longer needed.
**Note:** CI is currently failing due to a Clippy warning, but this will be resolved once #385 is merged.

Remove obsolete reset_admin_password function

---

CHANGELOG.md
src/graphql/node/input.rs

Handle configuration conversion failures explicitly

---

CHANGELOG.md
Cargo.toml
src/graphql/account.rs

Change `maxParallelSession` type to `Option<u8>`

---

CHANGELOG.md
examples/minireview.rs
src/backend.rs
src/graphql.rs
src/graphql/customer.rs
src/graphql/node.rs
src/graphql/node/control.rs
src/graphql/node/crud.rs
src/graphql/node/input.rs
src/graphql/node/status.rs

- Add `NetworksAgentKeysPair` structure that stores the internal
networks and a list of agent information that use that networks.
- Rename the `broadcast_internal_networks` method of to `AgentManager`
trait to `send_agent_specific_internal_networks`.
- Change the argument type of `send_agent_specific_internal_networks`
method from `HostNetworkGroup` to `NetworksTargetAgentKeysPair` array.
- Remove the part that broadcasts when registering a Central Management
Server node from the `insertNode` GraphQL API.
- Modify the `removeCustomers`, `updateCustomer` GraphQL API to
generate information about internal networks as
`Vec<NetworksAgentKeysPair>` instead of `HostNetworkGroup`.
- Rename `get_customer_id_of_node` to `agent_keys_by_customer_id` as
the functionality of `get_customer_id_of_node` …

Modify to broadcast the correct internal networks

---

CHANGELOG.md
src/graphql.rs
src/graphql/account.rs
src/graphql/node/control.rs
src/graphql/node/status.rs
src/graphql/trusted_domain.rs

- Removed the `username` parameter from the language and theme APIs to prevent unauthorized modifications and enforce JWT-based authentication.
Close: #378

Fix improper access control in GraphQL APIs

---

CHANGELOG.md
Cargo.toml

This fixes event filtering by multiple IP addresses for `ExternalDdos`, `MultiHostPortScan`, and `RdpBruteForce`.
This would allow applications depending on review-web to use up-to-date review-database, benefiting from its bug fixes and improvements.

Update review-database to 0.37.0

---

src/graphql/node.rs

closes #446
- Change host_name parameter to hostname in gen_agent_key function
- Maintain consistency with other parts of the codebase that already use hostname

Change host_name to hostname in `gen_agent_key()`

---

src/graphql/customer.rs
src/graphql/node/control.rs
src/graphql/node/status.rs
src/graphql/sampling.rs
src/graphql/trusted_domain.rs

Closes #413
Removes unnecessary explicit scope blocks in RocksDB operations following the
Send/Sync trait improvements in RocksDB 0.23.0.
Before:
```rust
let id = {
let store = crate::graphql::get_store(ctx).await?;
let map = store.sampling_policy_map();
map.put(pol.clone())?
};
```
After:
```rust
let store = crate::graphql::get_store(ctx).await?;
let map = store.sampling_policy_map();
let id = map.put(pol.clone())?;
```

Remove explicit scopes due to RocksDB 0.23.0

---

CHANGELOG.md
Cargo.toml
src/graphql/triage.rs

- Add `raw_event_kind` field to `PacketAttrInput` and `PacketAttr`.
- Add `UInteger`, `Vector`, `IpAddr`, `Bool` variants to `ValueKind` enum.
Close: #459
- Triage GraphQL API Test
- Insert triage & result
- Update Triage & result

Modify code related to the packet attribute triage

---

CHANGELOG.md
Cargo.toml
src/graphql/event.rs
src/graphql/node.rs
src/graphql/node/control.rs
src/graphql/node/crud.rs
src/graphql/node/input.rs
src/graphql/node/status.rs

- Add `ExternalService`, `ExternalServiceSnapshot` structs and related enums(`ExternalServiceStatus`, `ExternalServiceKind`).
- Replace `Option<GigantoInput>` with `Vec<ExternalServiceInput>` in `NodeInput` and `NodeDraftInput`.
- Remove `Giganto` and `GigantoInput` structs.
Close: #398
- node management GraphQL API Test
- insertNode & result
- applyNode & result
- updateDraftNode + applyNode & result

Modify the code related to node management

---

CHANGELOG.md
src/graphql/account.rs

Close: #439 
* Prevent system administrator creation via `insert_account`
* Prevent system administrator update via `update_account`
* not `SYSTEM_ADMINISTRATOR` -> `SYSTEM_ADMINISTRATOR` (x)
* `SYSTEM_ADMINISTRATOR` -> not `SYSTEM_ADMINISTRATOR` (x) 
* Fix broken test cases due to function changes

Disallow the creation of a new system administrator

---

src/graphql.rs
src/graphql/account.rs
src/graphql/cert.rs
src/graphql/customer.rs
src/graphql/event.rs
src/graphql/event/group.rs
src/graphql/node/control.rs
src/graphql/outlier.rs
src/lib.rs

Closes: #518 
Note:
Retrieved `username` value from `ctx` for logging purpose.
Future logs will follow the same pattern to include usernames where applicable.

Refactor log messages for consistency and clarity

---

CHANGELOG.md
Cargo.toml
src/graphql/node/crud.rs
src/graphql/node/status.rs
src/graphql/tidb.rs

Close: #525 
- Added `confidence` field to TidbRule struct.
- Fixed test code to check duplicate of node hostname.
[Enforce unique hostnames for nodes](https://github.com/petabi/review-database/commit/3fea24c6bfeaf3cc827a44335b957ffa90d9f7ef)
Pending:

Add confidence field to TidbRule GraphQL API

---

src/graphql/account.rs
src/graphql/allow_network.rs
src/graphql/block_network.rs
src/graphql/customer.rs
src/graphql/db_management.rs
src/graphql/network.rs
src/graphql/node/control.rs
src/graphql/node/crud.rs
src/graphql/node/status.rs
src/graphql/template.rs
src/graphql/tidb.rs
src/graphql/traffic_filter.rs
src/graphql/triage/policy.rs
src/graphql/triage/response.rs
src/graphql/trusted_domain.rs
src/lib.rs

Closes: #547
Some cases from the initial draft on our private wiki are missing in the current code:
- Requests handled directly by the web UI without triggering any GraphQL calls
- Logs related to time series policies (could not locate the relevant code paths)
- Logs related to traffic filters (the name of the traffic filter could not be retrieved)
- Other functionalities that appear to be outside the scope of review-web

Add logs for audit purposes
