- Cargo.toml
- src/graphql/event.rs
- src/graphql/filter.rs
- src/graphql/node.rs
Modified since the database changed
> Add `learning_methods` and `confidence` to `FilterInput`

- .github/workflows/ci.yml
- Cargo.toml
- examples/minireview.rs
A skeleton code to write a new example. This will be to demonstrate how to use this crate, and used as a test server to run the GraphQL API for integration testing.
> Add an example target, minireview

- Cargo.toml
- examples/minireview.rs
> Implement minireview

- CHANGELOG.md
- Cargo.toml
- src/graphql/event.rs
petabi/review-database#63
* Extend HttpThreat to use all of it's original fields
* Add `matched_to` field to contain the matched patterns
> Extend HttpThreat fields and add matched_to field

- CHANGELOG.md
- Cargo.toml
- src/graphql/event.rs
Add `confidence` field to `DomainGenerationAlgorithm` event
> add confidence field to DGA event

- CHANGELOG.md
- Cargo.toml
- src/graphql.rs
- src/graphql/event.rs
- src/lib.rs
> Added `eventstream` Graphql API to fetch events periodically

- CHANGELOG.md
- Cargo.toml
- examples/minireview.rs
- src/graphql.rs
- src/graphql/db_management.rs
- src/graphql/trusted_user_agent.rs
- Add the ability to list/insert/remove/update/apply graphql api for `trusted user agent`.
reference: https://github.com/aicers/hog/issues/414
> Added graphql api for trusted user agent

- src/graphql.rs
- src/graphql/trusted_user_agent.rs
- Apply `Arc<RwLock<Store>>>` to `trusted user agent` graphql api.
> Modify `trusted user agent` graphql api

- CHANGELOG.md
- Cargo.toml
- src/graphql/event.rs
https://github.com/petabi/review-database/pull/116
> Modify `BruteForce` events

- CHANGELOG.md
- Cargo.toml
- src/graphql/event.rs
https://github.com/petabi/review-database/issues/118
> Add BlockList events

- CHANGELOG.md
- Cargo.toml
> release 0.14.2

- CHANGELOG.md
- examples/minireview.rs
- src/graphql.rs
- src/graphql/customer.rs
- src/graphql/data_source.rs
- src/graphql/model.rs
- src/graphql/network.rs
- src/graphql/node/control.rs
- src/graphql/node/crud.rs
- src/graphql/outlier.rs
- src/graphql/sampling.rs
- src/graphql/triage/policy.rs
- src/lib.rs
> Modify outlier query to read outlier events from Rocks db

- CHANGELOG.md
- Cargo.toml
- src/graphql/data_source.rs
- src/graphql/event.rs
- src/graphql/event/dcerpc.rs
- src/graphql/event/ftp.rs
- src/graphql/event/http.rs
- src/graphql/event/kerberos.rs
- src/graphql/event/ldap.rs
- src/graphql/event/mqtt.rs
- src/graphql/event/nfs.rs
- src/graphql/event/ntlm.rs
- src/graphql/event/rdp.rs
- src/graphql/event/smb.rs
- src/graphql/event/smtp.rs
- src/graphql/event/ssh.rs
- src/graphql/event/tls.rs
- src/graphql/node/control.rs
- src/graphql/tidb.rs
- src/lib.rs
> Add block list event to all protocols

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.14.4

- CHANGELOG.md
> Modify node fields in CHANGELOG

- Cargo.toml
- src/graphql/category.rs
- src/graphql/cluster.rs
- src/graphql/event/conn.rs
- src/graphql/node.rs
- src/graphql/node/crud.rs
- src/graphql/triage/policy.rs
> Update review-database to 0.22.1

- CHANGELOG.md
- Cargo.toml
> release 0.17.0

- CHANGELOG.md
- Cargo.toml
- src/graphql/cluster.rs
- src/graphql/qualifier.rs
- src/graphql/status.rs
- src/graphql/tidb.rs
pending on discussion in petabi/review-database#188 and petabi/review-database#171
> Update review-database to 0.24.0

- CHANGELOG.md
- Cargo.toml
> Release 0.18.0

- CHANGELOG.md
- Cargo.toml
- src/auth/store.rs
- src/graphql.rs
- src/graphql/account.rs
- src/graphql/allow_network.rs
- src/graphql/block_network.rs
- src/graphql/category.rs
- src/graphql/customer.rs
- src/graphql/data_source.rs
- src/graphql/event.rs
- src/graphql/filter.rs
- src/graphql/indicator.rs
- src/graphql/model.rs
- src/graphql/network.rs
- src/graphql/node.rs
- src/graphql/node/crud.rs
- src/graphql/node/input.rs
- src/graphql/outlier.rs
- src/graphql/qualifier.rs
- src/graphql/sampling.rs
- src/graphql/statistics.rs
- src/graphql/status.rs
- src/graphql/tags/event_tag.rs
- src/graphql/tags/workflow_tag.rs
- src/graphql/template.rs
- src/graphql/tor_exit_node.rs
- src/graphql/triage/policy.rs
- src/graphql/triage/response.rs
This pull request updates the dependency on `review-database` to version 0.25. Given the significant API changes introduced since version 0.24, modifications to `review-web` are necessary to ensure compatibility with the new `review-database` API.
- **Dependency Update**: The `review-database` dependency in `review-web` is updated to version 0.25.0.
- **API Compatibility**: Adjustments have been made to `review-web` to comply with the new `review-database` API.
> Update the dependency on review-database to v0.25

- Cargo.toml
- src/auth/jwt.rs
- src/graphql.rs
- src/graphql/outlier.rs
- src/graphql/statistics.rs
> Update Chrono to 0.4.35 which deprecates some methods

- CHANGELOG.md
- Cargo.toml
- src/graphql.rs
- src/graphql/node/control.rs
> Add node shutdown

- CHANGELOG.md
- Cargo.toml
- examples/minireview.rs
- src/graphql.rs
> Add `AgentManager::{get|set}_config`

- CHANGELOG.md
- src/graphql/node/process.rs
> Fix issue with processList query

- .gitignore
- CHANGELOG.md
- Cargo.toml
- src/graphql.rs
- src/graphql/event.rs
- src/graphql/node.rs
- src/graphql/node/control.rs
- src/graphql/node/crud.rs
- src/graphql/node/input.rs
- src/graphql/node/status.rs
closes https://github.com/aicers/review-web/issues/127
> Make Node have `name_draft`, `settings` and `settings_draft` fields and make following changes due to Node change

- CHANGELOG.md
- Cargo.toml
> Release 0.19.0

- CHANGELOG.md
- src/graphql/node.rs
- src/graphql/node/control.rs
- src/graphql/node/status.rs
> Add module's config to `node_status_list`

- CHANGELOG.md
- src/graphql/node.rs
- src/graphql/node/control.rs
- src/graphql/node/status.rs
Reverts aicers/review-web#164
#177 의 수정사항을 먼저 반영한 후에 #164 의 수정사항을  반영하기 위해 #164 를 revert 합니다.
review-web이  review-database에 종속되므로, 최대한 review-database 변경을 우선으로 고려한 다음에 review-web 자체의 변경사항을 고려하는 순서로 merge 하기 위함입니다.
@sehkone @BLYKIM
> Revert "Add module's config to `node_status_list`"

- Cargo.toml
- src/graphql.rs
- src/graphql/event.rs
- src/graphql/node.rs
- src/graphql/node/control.rs
- src/graphql/node/crud.rs
- src/graphql/node/input.rs
pending on #169
@sophie-cluml @sehkone, could you please take a look at the modification regarding to `Node`. I went through the discussion that I have access to, but I am not entirely confident that I grasped all the recent design changes to the `Node` struct and the update algorithm. Please let me know if further modification is needed. Thanks.
> Update node interface

- CHANGELOG.md
- src/graphql/node/control.rs
> Use `set_config` and `halt` instead of `send_and_recv` of `AgentManager`

- CHANGELOG.md
- examples/minireview.rs
- src/graphql.rs
- src/graphql/node/control.rs
> Remove `AgentManager::send_and_recv`

- CHANGELOG.md
- src/graphql.rs
- src/graphql/account.rs
- src/graphql/allow_network.rs
- src/graphql/block_network.rs
- src/graphql/category.rs
- src/graphql/cluster.rs
- src/graphql/customer.rs
- src/graphql/data_source.rs
- src/graphql/event.rs
- src/graphql/model.rs
- src/graphql/network.rs
- src/graphql/node/crud.rs
- src/graphql/node/status.rs
- src/graphql/outlier.rs
- src/graphql/qualifier.rs
- src/graphql/sampling.rs
- src/graphql/statistics.rs
- src/graphql/status.rs
- src/graphql/template.rs
- src/graphql/tor_exit_node.rs
- src/graphql/triage/policy.rs
- src/graphql/triage/response.rs
- src/graphql/trusted_domain.rs
- src/graphql/trusted_user_agent.rs
Validation function created and added validation of pagination combinations to `nodeStatusList` along with other 25 graphql queries (26 in total).
Closes: #180 ;
> Add valid parameter checking for GraphQL queries

- CHANGELOG.md
- src/graphql/node.rs
- src/graphql/node/status.rs
- Remove `Giganto` from `NodeStatus`
Close: #189
> Fix `node_status_list` response

- src/graphql/node/status.rs
> Add unit test for `nodeStatusList`

- CHANGELOG.md
- Cargo.toml
- src/graphql.rs
- src/graphql/account.rs
- src/lib.rs
> Add resetAdminPassword Mutation with Local IP Restriction

- CHANGELOG.md
- Cargo.toml
> Release 0.20.0

- CHANGELOG.md
> Correct the release date of `0.20.0` to `2024-04-25`

- CHANGELOG.md
- Cargo.toml
- src/archive.rs
- src/graphql.rs
- src/graphql/account.rs
- src/graphql/customer.rs
- src/graphql/event.rs
- src/graphql/event/conn.rs
- src/graphql/event/group.rs
- src/graphql/event/http.rs
- src/graphql/event/ntlm.rs
- src/graphql/event/smtp.rs
- src/graphql/event/ssh.rs
- src/graphql/event/tls.rs
- src/graphql/network.rs
- src/graphql/node/control.rs
- src/graphql/node/status.rs
- src/graphql/outlier.rs
- src/graphql/template.rs
- src/graphql/traffic_filter.rs
- src/lib.rs
- Update dependencies version.
- Fix code based on a dependency update.
- Fix code associated with changed fields in events detected in HTTP, SMTP, CONN, NTLM, SSH, and TLS protocols.
- Fix code based on changes in test code results.
- Split the contents of the structures `Mutation`,`Query` into substructures.
Close: #230
> Bump dependencies

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
> Updated version of rustls and fixed related code

- examples/minireview.rs
- Modify to read the admin account from the env var `REVIEW_ADMIN`.
Related Issue: #38
Closes: #240
> Modify minireview to read admin account.

- examples/minireview.rs
- Delete ? operator
Closes: #243
> Fix `minireview`

- CHANGELOG.md
- Cargo.toml
- src/graphql.rs
- src/graphql/customer.rs
- src/graphql/event.rs
- src/graphql/event/group.rs
- src/graphql/node.rs
- src/graphql/node/control.rs
- src/graphql/node/crud.rs
- src/graphql/node/input.rs
- src/graphql/node/status.rs
`ApplyNode`와 관련 함수, 테스트 코드 등은 많은 변경점이 있어 #251 이슈에서 다룰 수 있습니다.
- Modify related CRUD APIs
Closes: https://github.com/aicers/review-web/issues/245
Closes: #227
> Modify `Node`, `NodeProfile`

- CHANGELOG.md
- Cargo.toml
- src/graphql/account.rs
- src/graphql/triage.rs
resolves #252 
This PR is worked upon #249, so this PR needs to stay as WIP until that one is merged.
> Update review-database to 0.29.1

- Cargo.toml
- src/auth/jwt.rs
> Use LazyLock to replace lazy-static

- CHANGELOG.md
- src/graphql/event.rs
- src/graphql/event/conn.rs
- src/graphql/event/dcerpc.rs
- src/graphql/event/dns.rs
- src/graphql/event/ftp.rs
> Use `StringNumber` for integers beyond `i32` - part1

- CHANGELOG.md
- src/graphql/event/http.rs
- src/graphql/event/kerberos.rs
- src/graphql/event/ldap.rs
- src/graphql/event/log.rs
> Use `StringNumber` for integers beyond `i32` - part2

- CHANGELOG.md
- src/graphql/account.rs
- src/graphql/cluster.rs
- src/graphql/event/network.rs
- src/graphql/indicator.rs
> Use `StringNumber` for integers beyond `i32` - part3

- Cargo.toml
- src/lib.rs
> Modify to use ring as the rustls cryptography library option

- CHANGELOG.md
- src/graphql/model.rs
- src/graphql/statistics.rs
- src/graphql/template.rs
> Use `StringNumber` for integers beyond `i32` - part4

- CHANGELOG.md
- examples/minireview.rs
- src/backend.rs
- src/graphql.rs
- src/graphql/event.rs
- src/graphql/node/control.rs
- src/graphql/node/status.rs
> Update GraphQL API `applyNode`

- CHANGELOG.md
- Cargo.toml
- src/graphql/event.rs
- src/graphql/event/bootp.rs
- src/graphql/event/dhcp.rs
- src/graphql/event/tls.rs
Close #254 
- Add BlockListBootp, BlockListDhcp, SuspiciousTlsTraffic event.
> Add BlockListBootp, BlockListDhcp, SuspiciousTlsTraffic event

- CHANGELOG.md
- src/backend.rs
- src/graphql/node.rs
- src/graphql/node/control.rs
- src/graphql/node/crud.rs
- src/graphql/node/status.rs
close #279 
-- 
This commit is worked on top of #280
> Update the GraphQL API `nodeStatusList`

- CHANGELOG.md
> Fix wrong CHANGELOG

- src/graphql/trusted_user_agent.rs
`TrustedUserAgent` doesn't need to implement `FromKeyValue`.
> Remove unused impl

- src/graphql/node/control.rs
> Remove warning from cargo test

- CHANGELOG.md
- Cargo.toml
- examples/minireview.rs
- src/backend.rs
- src/graphql.rs
- src/graphql/node.rs
- src/graphql/node/control.rs
- src/graphql/node/status.rs
> Update review-protocol to 0.7.0

- CHANGELOG.md
- src/graphql/node.rs
- src/graphql/node/status.rs
> Update `nodeStatusList` GraphQL API

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.22.0

- Cargo.toml
review-protocol is no longer used in the project.
> Remove unused dependency

- CHANGELOG.md
- src/graphql/event.rs
- src/graphql/node/control.rs
- src/graphql/node/crud.rs
- src/graphql/node/input.rs
- src/graphql/node/status.rs
> Validate node input in `applyNode` GraphQL API

- src/graphql/outlier.rs
> Refine comment in `rankedOutliers` for clarity

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.24.0

- CHANGELOG.md
- src/graphql/node/control.rs
> Fix `applyNode` GraphQL API

- .github/workflows/ci.yml
- examples/minireview.rs
- src/graphql.rs
- src/graphql/account.rs
- src/graphql/allow_network.rs
- src/graphql/block_network.rs
- src/graphql/customer.rs
- src/graphql/data_source.rs
- src/graphql/event.rs
- src/graphql/event/group.rs
- src/graphql/filter.rs
- src/graphql/network.rs
- src/graphql/node/control.rs
- src/graphql/node/crud.rs
- src/graphql/node/status.rs
- src/graphql/outlier.rs
- src/graphql/sampling.rs
- src/graphql/tags/network_tag.rs
- src/graphql/template.rs
- src/graphql/tidb.rs
- src/graphql/tor_exit_node.rs
- src/graphql/traffic_filter.rs
- src/graphql/triage.rs
- src/graphql/trusted_domain.rs
> Fix Clippy warnings and enforce Clippy check in test code

- CHANGELOG.md
- Cargo.toml
> Update review-database to 0.33.1

- src/archive.rs
- src/lib.rs
> Refactor `unwrap`

- CHANGELOG.md
- Cargo.toml
> Bump review-database to 0.34.0

- src/graphql/event/conn.rs
- src/graphql/event/dns.rs
- src/graphql/event/ftp.rs
- src/graphql/event/http.rs
- src/graphql/event/kerberos.rs
- src/graphql/event/ldap.rs
- src/graphql/event/mqtt.rs
- src/graphql/event/nfs.rs
- src/graphql/event/tls.rs
> Modify `Vec<T>` to `&[T]`

- Cargo.toml
- src/archive.rs
- src/graphql/node/status.rs
async-graphql-axum is updated accordingly.
Close: #393
> Update axum to 0.8

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.25.0

- src/graphql/node/crud.rs
- src/graphql/node/input.rs
> Enhance error logs by adding agent information

- CHANGELOG.md
- src/graphql/node/crud.rs
- src/graphql/node/input.rs
Close: #410
- This PR primarily addresses issue #410 by fixing the missing configuration error in updateNodeDraft. 
- Additionally, minor formatting improvements have been made to the CHANGELOG with "Rewrap" VSCode extension, without altering the content.
> Fix missing config error in `updateNodeDraft` 

- CHANGELOG.md
- Cargo.toml
- src/graphql/account.rs
> Modify GraphQL APIs related to account

- src/graphql/tidb.rs
- src/lib.rs
> Fix Clippy warnings caused by rustc 1.86.0

- CHANGELOG.md
- src/graphql.rs
- src/graphql/trusted_user_agent.rs
> Remove unused `get_trusted_user_agent_list` function

- .github/workflows/doc.yml
> Update GitHub actions in doc.yml

- CHANGELOG.md
- Cargo.toml
- src/graphql/event.rs
- src/graphql/event/tls.rs
Close #426 
- Add `confidence` field to `BlockListTlsFields`
> Add confidence field to BlockListTlsFields

- CHANGELOG.md
- src/graphql/event.rs
- src/graphql/event/group.rs
~WIP: The version of review-database should be updated to use a tag, not a rev.~ Updated to the merged commit.
Closes #417
> Change the sensors filter logic for the event list

- CHANGELOG.md
- src/graphql/account.rs
- src/graphql/cluster.rs
- src/graphql/network.rs
- src/graphql/triage/response.rs
> Replace `Vec<u32>` to `Vec<ID>` for `customer_ids`

- CHANGELOG.md
- src/graphql/trusted_domain.rs
> Support removing multiple trusted domains

- CHANGELOG.md
- src/graphql/account.rs
> Create `myAccount` GraphQL API

- src/graphql.rs
> Fix Clippy warnings caused by rustc 1.87.0

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.26.0

- .github/workflows/release.yml
> Add GitHub Actions for automated releases

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.27.0

- CHANGELOG.md
> Move recent changelog entries to `Unreleased`

- src/graphql/event/dns.rs
> Restore `src_port` in `DnsCovertChannel`

- .github/workflows/ci.yml
- .github/workflows/doc.yml
- .github/workflows/release.yml
> Update `actions/checkout` to v5

- CHANGELOG.md
- Cargo.toml
- src/graphql/event/http.rs
> Add start/end time to RepeatedHttpSession

- src/auth/jwt.rs
> Fix clippy errors

- examples/minireview.rs
> Update CI to check all targets with clippy

- .github/workflows/add-to-project.yml
> Do not use `pull_request_target`
